# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Monique Katsuki, MD, MPH, FACOG"                    # Your name
  description: "OB/Gyn Physician-Scientist"   # A brief slogan (optional)
  image: img/my_image.jpg

  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: img/myk.image.JPG
    
    # your sub-pages
    left:
      - text: "Blog"
        href: blog/index.qmd
      - text: "Dashboard"
        href: dashboard/BMI_analyses.qmd
      - text: "CV"
        href: cv/index.html
 
    # your social media handles
    right:
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/monique-katsuki-md-mph-35a9b029b
      - icon: envelope
        text: email
        href: mailto:mxk1220@case.edu 


# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Marvin Schmitt CC BY-SA 4.0</span>
    center: |
      <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">View the tutorial for this template!</a></span>
    right: |
      <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true